#pragma config(Sensor, in1,    right,               sensorTouch)
#pragma config(Sensor, in2,    left,                sensorTouch)
#pragma config(Sensor, in3,    top,                 sensorTouch)
#pragma config(Sensor, in4,    back,                sensorTouch)
#pragma config(Motor,  port1,           Audio,                tmotorAudio)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void PinkPanther()
{
  //        160 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(Eighth))
  PlayTone(    0,   68); wait1Msec( 750);  // Note(Rest, Duration(Half))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(Eighth))
  PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(Eighth))
  PlayTone(    0,   68); wait1Msec( 750);  // Note(Rest, Duration(Half))
  PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(Eighth))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(16th))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(Eighth))
  PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(Eighth))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(16th))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(16th))
  PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(Eighth))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(16th))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(  932,   68); wait1Msec( 750);  // Note(A#, Duration(Half))
  PlayTone(    0,   68); wait1Msec( 750);  // Note(Rest, Duration(Half))
  PlayTone(  880,    8); wait1Msec(  94);  // Note(A, Duration(16th))
  PlayTone(  783,    8); wait1Msec(  94);  // Note(G, Duration(16th))
  PlayTone(  659,    8); wait1Msec(  94);  // Note(E, Duration(16th))
  PlayTone(  587,    8); wait1Msec(  94);  // Note(D, Duration(16th))
  PlayTone(  659,   68); wait1Msec( 750);  // Note(E, Duration(Half))
  return;
}

task Playsongs()
{
	PinkPanther();
	wait1Msec(50);
}

task main()
{
	bMotorFlippedMode[port1] = 1;
	bMotorFlippedMode[port4] = 1;
	bMotorFlippedMode[port5] = 1;
	bVexAutonomousMode = false;

	while(true)
	{
		if (SensorValue[right] == 1)
		{
			wait1Msec(5000);
		}

		else if (SensorValue[left] == 1)
		{
			wait1Msec(5000);
		}
		else if (SensorValue[top] == 1)
		{
			wait1Msec(5000);
		}
		else if (SensorValue[back] == 1)
		{
			StartTask(Playsongs);
		}

		{

	    motor[port1] = vexRT[Ch2];
	    motor[port2] = vexRT[Ch2];
	    motor[port3] = vexRT[Ch2];
      motor[port4] = vexRT[Ch2];
	    motor[port5] = vexRT[Ch2];
	    motor[port6] = vexRT[Ch2];
  	  motor[port7] = vexRT[Ch1]/2;
  	  motor[port8] = vexRT[Ch5];
  	}
  }
}
