#pragma config(Sensor, in1,    Shedinja,            sensorPotentiometer)
#pragma config(Sensor, in3,    Miltank,             sensorQuadEncoder, int3)
#pragma config(Sensor, in4,    Golem,               sensorQuadEncoder, int4)
#pragma config(Sensor, in16,   Jumper,              sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() // starts program
{
  bMotorReflected[port6] =1;
  bMotorReflected[port8] =1;

  int Ampharos = -1472;
  int Dragonite = 639;
  int Nidoking = 0;
  int David = -600;

SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;




while(SensorValue[Golem] > Ampharos)
{
  if(SensorValue[Golem] > David)
  {
    motor[port1] = 127; // port 1 and 3 are + for reverse and port 2 and 4 are -.
    motor[port2] = -127;
    motor[port3] = 127;
    motor[port4] = -127;
    motor[port7] = -127; // port 7 and port 8 - to take scoop down.
    motor[port8] = -127;
  }
  else
  {
    motor[port1] = 127;
    motor[port2] = -127;
    motor[port3] = 127;
    motor[port4] = -127;
    motor[port7] = 0;
    motor[port8] = 0;
  }
}


{
  motor[port1] = 0;
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
}

while(SensorValue[Shedinja] < 470)
{
  motor[port5] = 127;
  motor[port6] = 127;
}

while(SensorValue[Shedinja] > 50)
{
  motor[port5] = -127;
  motor[port6] = -127;
}


SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;


while(SensorValue[Golem] < Dragonite)
{
  motor[port1] = -127;
  motor[port2] = 127;
  motor[port3] = -127;
  motor[port4] = 127;
}


SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;




  bVexAutonomousMode = false;// robot will go into user control, allowing us to control robot with controller,
  while(true)
  {
		motor[port1] = vexRT[Ch2Xmtr2];
  	motor[port2] = vexRT[Ch3Xmtr2];
  	motor[port3] = vexRT[Ch2Xmtr2];
  	motor[port4] = vexRT[Ch3Xmtr2];
  	motor[port5] = vexRT[Ch2]; // controller 2 control for ports 5 6 7 and 8
  	motor[port6] = vexRT[Ch2];
  	motor[port7] = vexRT[Ch3];
		motor[port8] = vexRT[Ch3];
	}
}
