#pragma config(Sensor, in1,    Shedinja,            sensorPotentiometer)
#pragma config(Sensor, in3,    Miltank,             sensorQuadEncoder, int3)
#pragma config(Sensor, in4,    Golem,               sensorQuadEncoder, int4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

  bMotorReflected[port6] =1;
  bMotorReflected[port8] =1;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{


  int Ampharos = -1470;
  int Dragonite = 639;
  int David = -600;

SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;




while(SensorValue[Golem] > Ampharos)
{
  if(SensorValue[Golem] > David)
  {
    motor[port1] = 127; // port 1 and 3 are + for reverse and port 2 and 4 are -.
    motor[port2] = -127;
    motor[port3] = 127;
    motor[port4] = -127;
    motor[port7] = -127; // port 7 and port 8 - to take scoop down.
    motor[port8] = -127;
  }
  else
  {
    motor[port1] = 127;
    motor[port2] = -127;
    motor[port3] = 127;
    motor[port4] = -127;
    motor[port7] = 0;
    motor[port8] = 0;
  }
}


{
  motor[port1] = 0;
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
}

while(SensorValue[Shedinja] < 470)
{
  motor[port5] = 127;
  motor[port6] = 127;
}

{
  motor[port1] = 0;
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;
  motor[port6] = 0;
  motor[port7] = 0;
  motor[port8] = 0;
  wait1Msec(15000);
}





while(SensorValue[Shedinja] > 50)
{
  motor[port5] = -127;
  motor[port6] = -127;
}


SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;

{
  motor[port1] = 0;
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;
  motor[port6] = 0;
  motor[port7] = 0;
  motor[port8] = 0;
}





  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

	  motor[port1] = vexRT[Ch2Xmtr2];
  	motor[port2] = vexRT[Ch3Xmtr2];
  	motor[port3] = vexRT[Ch2Xmtr2];
  	motor[port4] = vexRT[Ch3Xmtr2];
  	motor[port5] = vexRT[Ch2]; // controller 2 control for ports 5 6 7 and 8
  	motor[port6] = vexRT[Ch2];
  	motor[port7] = vexRT[Ch3];
		motor[port8] = vexRT[Ch3];
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
