#pragma config(Sensor, in1,    Scooper,             sensorPotentiometer)
#pragma config(Sensor, in2,    Dumper,              sensorPotentiometer)
#pragma config(Sensor, in3,    Right,               sensorQuadEncoder, int3)
#pragma config(Sensor, in4,    Left,                sensorQuadEncoder, int4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(123)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	 bMotorReflected[port3] =1;
  bMotorReflected[port4] =1;
  bMotorReflected[port6] =1;
  bMotorReflected[port8] =1;

  {
    SensorValue[Right] = 0;
    SensorValue[Left] = 0;
  }

  while(SensorValue[Right] > -100) // step one drive back to give it space to bring scoop down
  {
    if (SensorValue[Right] > -90)
    {

      motor[port1] = -127;
      motor[port2] = -127;
      motor[port3] = -127;
      motor[port4] = -127;
    }
    else
    {
      motor[port1] = 0;
      motor[port2] = 0;
      motor[port3] = 0;
      motor[port4] = 0;
    }
  }

  {
    motor[port1] = 0;
    motor[port2] = 0;
    motor[port3] = 0;
    motor[port4] = 0;
    motor[port5] = 0;
    motor[port6] = 0;
    motor[port7] = 0;
    motor[port8] = 0;
    wait1Msec(1000);
  }



  while(SensorValue[Scooper] > 20) // step two bring scoop down so we can dump when we want to
  {
    if(SensorValue[Scooper] > 75)
    {
      motor[port7] = -127;
      motor[port8] = -127;
    }
    else
    {
      motor[port7] = 0;
      motor[port8] = 0;
    }
  }

  {
    SensorValue[Right] = 0;
    SensorValue[Left] = 0;
  }


  while(SensorValue[Right] > -1400)// step three drives back to the wall to prepare for dumping
  {
    if(SensorValue[Right] > -1385)
    {

      motor[port1] = -127;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = -127;
	    motor[port3] = -127;
	    motor[port4] = -127;
    }
    else
    {
      motor[port1] = 0;
      motor[port2] = 0;
      motor[port3] = 0;
      motor[port4] = 0;
    }
  }

  {
    motor[port5] = 127;
    motor[port6] = 127;
    wait1Msec(3300);
  }

  {
    motor[port1] = 0;
    motor[port2] = 0;
    motor[port3] = 0;
    motor[port4] = 0;
    motor[port5] = 0;
    motor[port6] = 0;
    motor[port7] = 0;
    motor[port8] = 0;
    wait1Msec(1000);
  }



  AuonomousCodePlaceholderForTesting();


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  motor[port1] = vexRT[Ch3];
  	motor[port2] = vexRT[Ch3];
  	motor[port3] = vexRT[Ch2];
  	motor[port4] = vexRT[Ch2];
  	motor[port5] = vexRT[Ch2Xmtr2]; // controller 2 control for ports 5 6 7 and 8
  	motor[port6] = vexRT[Ch2Xmtr2];
  	motor[port7] = vexRT[Ch3Xmtr2];
		motor[port8] = vexRT[Ch3Xmtr2];
	}

	 UserControlCodePlaceholderForTesting();
}
