#pragma config(Sensor, in1,    Shedinja,            sensorPotentiometer)
#pragma config(Sensor, in3,    Miltank,             sensorQuadEncoder, int3)
#pragma config(Sensor, in4,    Golem,               sensorQuadEncoder, int4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() // starts program
{
  bMotorReflected[port6] =1;
  bMotorReflected[port8] =1;

SensorValue[Golem] = 0;
SensorValue[Miltank] = 0;


  bVexAutonomousMode = false;// robot will go into user control, allowing us to control robot with controller,
  while(true)
  {
		motor[port1] = vexRT[Ch2Xmtr2];
  	motor[port2] = vexRT[Ch3Xmtr2];
  	motor[port3] = vexRT[Ch2Xmtr2];
  	motor[port4] = vexRT[Ch3Xmtr2];
  	motor[port5] = vexRT[Ch2]; // controller 2 control for ports 5 6 7 and 8
  	motor[port6] = vexRT[Ch2];
  	motor[port7] = vexRT[Ch3];
		motor[port8] = vexRT[Ch3];
	}
}
