#pragma config(Sensor, in1,    Scooper,             sensorPotentiometer)
#pragma config(Sensor, in2,    Dumper,              sensorPotentiometer, int3)
#pragma config(Sensor, in3,    Right,               sensorQuadEncoder, int3)
#pragma config(Sensor, in4,    Left,                sensorQuadEncoder, int4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main() // starts program
{


  bMotorReflected[port3] =1;
  bMotorReflected[port4] =1;
  bMotorReflected[port6] =1;
  bMotorReflected[port8] =1;

  {
    SensorValue[Right] = 0;
    SensorValue[Left] = 0;
  }

    {
      motor[port1] = -127;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = -127;
	    motor[port3] = -127;
	    motor[port4] = -127;
	    motor[port7] = -127;
      motor[port8] = -127;
	    wait1Msec(1800);
    }

    {
      motor[port1] = 0;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 0;
	    motor[port3] = 0;
	    motor[port4] = 0;
	    motor[port5] = 0;
	    motor[port6] = 0;
	    motor[port7] = 0;
      motor[port8] = 0;
	    wait1Msec(1000);
    }

     {
	    motor[port5] = -64;
      motor[port6] = -64;
	    wait1Msec(1100);
    }





    {
      motor[port1] = 0;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 0;
	    motor[port3] = 0;
	    motor[port4] = 0;
	    motor[port7] = 0;
      motor[port8] = 0;
	    wait1Msec(1000);
    }

      {
	    motor[port5] = -60;// will go forward at full power while sensorvalue is greater than given number
	    motor[port6] = -60;
	    wait1Msec(75);
	  }

	  {
      motor[port1] = 0;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 0;
	    motor[port3] = 0;
	    motor[port4] = 0;
	    motor[port5] = 0;
	    motor[port6] = 0;
	    motor[port7] = 0;
      motor[port8] = 0;
	    wait1Msec(1000);
	  }

    {
      motor[port1] = 127;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 127;
	    motor[port3] = 127;
	    motor[port4] = 127;
	    wait1Msec(100);
	  }

	  {
      motor[port1] = 0;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 0;
	    motor[port3] = 0;
	    motor[port4] = 0;
	    motor[port5] = 0;
	    motor[port6] = 0;
	    motor[port7] = 0;
      motor[port8] = 0;
	    wait1Msec(1000);
    }

	  {
	    motor[port1] = -127;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = -127;
	    motor[port3] = 127;
	    motor[port4] = 127;
	    wait1Msec(400);
	  }

	  {
      motor[port1] = 0;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = 0;
	    motor[port3] = 0;
	    motor[port4] = 0;
	    motor[port5] = 0;
	    motor[port6] = 0;
	    motor[port7] = 0;
      motor[port8] = 0;
	    wait1Msec(1000);
    }

	  {
	    motor[port1] = -127;// will go forward at full power while sensorvalue is greater than given number
	    motor[port2] = -127;
	    motor[port3] = -127;
	    motor[port4] = -127;
	    wait1Msec(600);
	  }

  bVexAutonomousMode = false;// robot will go into user control, allowing us to control robot with controller,
  while(true)
  {
    motor[port1] = vexRT[Ch3];
  	motor[port2] = vexRT[Ch3];
  	motor[port3] = vexRT[Ch2];
  	motor[port4] = vexRT[Ch2];
  	motor[port5] = vexRT[Ch2Xmtr2]; // controller 2 control for ports 5 6 7 and 8
  	motor[port6] = vexRT[Ch2Xmtr2];
  	motor[port7] = vexRT[Ch3Xmtr2];
		motor[port8] = vexRT[Ch3Xmtr2];
    }
  }
